import { StarTwoTone } from '@mui/icons-material';
import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { strictEqual } from 'assert';
import { RootState, AppThunk } from '../../app/store';
import { db } from '../../firebase';
// import { fetchCount } from './counterAPI';

export interface TaskState {
  //taskが何個あるのか管理
  idCount: number;
  //storeに保存するtask一覧
  tasks: { id: string; title: string; completed: boolean }[];
  //taskのtitleを編集する際にどのtaskが選択されているか
  selectedTask: { id: string; title: string; completed: boolean };
  //Modalが開くか閉じるかのフラグ
  isModalOpen: boolean;
}

const initialState: TaskState = {
  idCount: 1,
  tasks: [],
  selectedTask: { id: '', title: '', completed: false },
  isModalOpen: false,
};

/*============================================
taskの全件取得
============================================*/
export const fetchTasks = createAsyncThunk('task/getAllTasks', async () => {
  //日付の降順にデータをソートしてtaskのデータを全件取得
  const res = await db.collection('tasks').orderBy('dateTime', 'desc').get();

  //レスポンスの整形
  const allTasks = res.docs.map((doc) => ({
    id: doc.id,
    title: doc.data().title,
    completed: doc.data().completed,
  }));
  const taskNumber = allTasks.length;
  const passData = { allTasks, taskNumber };
  return passData;
});

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// -------------------------------------------------------------------------------
// typically used to make async requests.
// export const incrementAsync = createAsyncThunk(
//   'counter/fetchCount',
//   async (amount: number) => {
//     const response = await fetchCount(amount);
//     // The value we return becomes the `fulfilled` action payload
//     return response.data;
//   }
// );

export const taskSlice = createSlice({
  name: 'task',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    //taskの作成
    createTask: (state, action) => {
      state.idCount++;
      const newTask = {
        id: state.idCount,
        title: action.payload,
        completed: false,
      };
      state.tasks = [newTask, ...state.tasks];
    },

    //taskの編集
    editTask: (state, action) => {
      //state.tasksの中から指定したtaskを抜き出している
      const task = state.tasks.find((t) => t.id === action.payload.id);
      if (task) {
        //抜き出したtaskのtitleを置き換える
        task.title = action.payload.title;
      }
    },

    //どのタスクを選択しているか管理
    selectTask: (state, action) => {
      state.selectedTask = action.payload;
    },

    //Modalを開くか閉じるかのフラグの管理
    handleModalOpen: (state, action) => {
      state.isModalOpen = action.payload;
    },

    //task完了、未完了のチェックを変更
    completeTask: (state, action) => {
      //state.tasksの中から指定したtaskを抜き出している
      const task = state.tasks.find((t) => t.id === action.payload.id);
      if (task) {
        //抜き出したtaskのcompletedを反転させる
        task.completed = !task.completed;
      }
    },

    //taskの削除
    deleteTask: (state, action) => {
      //指定したtask以外で新しくstate.tasksの配列を再作成している
      state.tasks = state.tasks.filter((t) => t.id !== action.payload.id);
    },

    // increment: (state) => {
    //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
    //   // doesn't actually mutate the state because it uses the Immer library,
    //   // which detects changes to a "draft state" and produces a brand new
    //   // immutable state based off those changes
    //   state.value += 1;
    // },
    // decrement: (state) => {
    //   state.value -= 1;
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload;
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.

  // extraReducers: (builder) => {
  //   builder
  //     .addCase(incrementAsync.pending, (state) => {
  //       state.status = 'loading';
  //     })
  //     .addCase(incrementAsync.fulfilled, (state, action) => {
  //       state.status = 'idle';
  //       state.value += action.payload;
  //     });
  // },
  extraReducers: (builder) => {
    //stateとactionの型が正しく推論されるためにbuilder関数を用いる
    builder.addCase(fetchTasks.fulfilled, (state, action) => {
      //action.payload === return passData
      state.tasks = action.payload.allTasks;
      state.idCount = action.payload.taskNumber;
    });
  },
});

export const {
  createTask,
  selectTask,
  handleModalOpen,
  editTask,
  completeTask,
  deleteTask,
} = taskSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectTasks = (state: RootState): TaskState['tasks'] =>
  state.task.tasks;
export const selectIsModalOpen = (state: RootState): TaskState['isModalOpen'] =>
  state.task.isModalOpen;
export const selectSelectedTask = (
  state: RootState
): TaskState['selectedTask'] => state.task.selectedTask;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectCount(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount));
//     }
//   };

export default taskSlice.reducer;
